# Generated by Django 5.2 on 2025-12-31 10:52

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='category_image/', verbose_name='Фотография')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': '1) Категория организации',
                'verbose_name_plural': '1) Категории организаций',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('short_title', models.CharField(blank=True, max_length=120, verbose_name='Короткое название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('cover_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[1920, 1080], upload_to='services/covers/', verbose_name='Обложка (фото)')),
                ('cover_video_url', models.URLField(blank=True, verbose_name='Видео (URL)')),
                ('has_360', models.BooleanField(default=False, verbose_name='Есть 360°')),
                ('view_360_url', models.URLField(blank=True, verbose_name='Ссылка на 360°')),
                ('price_type', models.CharField(choices=[('per_m2', 'Цена за м²'), ('fixed', 'Фиксированная цена'), ('hourly', 'Почасовая'), ('subscription', 'Абонентское обслуживание'), ('request', 'По запросу')], default='request', max_length=20, verbose_name='Тип цены')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена от')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Минимальная цена')),
                ('price_note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий к цене')),
                ('cta_text', models.CharField(default='Оставить заявку', max_length=120, verbose_name='Текст CTA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('business_types', models.ManyToManyField(blank=True, related_name='services', to='cms.categoryorganization', verbose_name='Категории бизнесов')),
            ],
            options={
                'verbose_name': '2) Услуга',
                'verbose_name_plural': '2) Услуги',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('included', 'Что входит в услугу'), ('zones', 'Уборка по зонам / помещениям'), ('chemistry', 'Используемые средства'), ('equipment', 'Оборудование и техника'), ('requirements', 'Требования к объекту'), ('conditions', 'Условия выполнения работ'), ('pricing', 'Стоимость и расчёт цены'), ('excluded', 'Что не входит в услугу'), ('extras', 'Дополнительные услуги'), ('quality', 'Контроль качества и ответственность'), ('clients', 'Кто уже заказывал эту услугу'), ('faq', 'Часто задаваемые вопросы')], max_length=32, verbose_name='Тип блока')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блока')),
                ('content', models.TextField(blank=True, verbose_name='Контент блока')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать блок')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': '3) Блок услуги',
                'verbose_name_plural': '3) Блоки услуги',
                'ordering': ['order', 'id'],
                'unique_together': {('service', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SectionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=10, verbose_name='Тип')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[1920, 1080], upload_to='services/sections/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, verbose_name='Видео URL (YouTube/Vimeo/файл)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='cms.servicesection', verbose_name='Блок')),
            ],
            options={
                'verbose_name': '4) Медиа блока',
                'verbose_name_plural': '4) Медиа блоков',
                'ordering': ['order', 'id'],
            },
        ),
    ]
