# Generated by Django 5.2 on 2025-12-31 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicesection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='servicesection',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='business_types',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='service',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_from',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_note',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_title',
        ),
        migrations.AddField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='cms.categoryorganization', verbose_name='Категория организации'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SectionMedia',
        ),
        migrations.DeleteModel(
            name='ServiceSection',
        ),
    ]
