# Generated by Django 5.2 on 2026-01-02 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_servicesection_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIncludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Пункт (что входит)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_items', to='cms.service', verbose_name='Услуга')),
            ],
        ),
    ]
