# Generated by Django 5.2 on 2026-01-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_serviceincludeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceZoneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('room', 'Комната'), ('kitchen', 'Кухня'), ('bath_wc', 'Ванная и туалет'), ('hall', 'Прихожая / входная группа'), ('office', 'Офис / рабочая зона'), ('warehouse', 'Склад / подсобка'), ('other', 'Другое')], max_length=30, verbose_name='Зона')),
                ('text', models.CharField(help_text='Один пункт = одна строка (например: Удаление пыли со всех поверхностей)', max_length=255, verbose_name='Пункт')),
                ('note', models.CharField(blank=True, help_text='Например: "ограничение 5 минут" или "сложные загрязнения не входит"', max_length=255, null=True, verbose_name='Примечание (опционально)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_items', to='cms.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Пункт по зонам',
                'verbose_name_plural': 'Пункты по зонам',
                'ordering': ['zone', 'order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ServiceIncludedItem',
        ),
    ]
