# Generated by Django 5.2 on 2026-01-02 11:04

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_servicezoneitem_delete_serviceincludeditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicezoneitem',
            name='note',
        ),
        migrations.CreateModel(
            name='ServiceChemicalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название средства')),
                ('description', models.CharField(blank=True, help_text='Например: Для кухни, удаления жира, рабочих поверхностей', max_length=255, null=True, verbose_name='Где и для чего применяется')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='services/chemicals/', verbose_name='Фотография средства')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_items', to='cms.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Используемое средство',
                'verbose_name_plural': 'Используемые средства',
                'ordering': ['order', 'id'],
            },
        ),
    ]
