# Generated by Django 5.2 on 2026-01-02 18:46

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_servicezoneitem_note_servicechemicalitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('description', models.CharField(blank=True, help_text='Например: Для глубокой химчистки мебели, мощное всасывание', max_length=255, null=True, verbose_name='Для чего используется / преимущества')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='services/equipment/', verbose_name='Фотография оборудования')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='cms.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Оборудование (услуги)',
                'verbose_name_plural': 'Оборудование (услуг)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='cms.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'FAQ (услуги)',
                'verbose_name_plural': 'FAQ (услуг)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
