# Generated by Django 5.2 on 2026-01-03 09:48

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_serviceequipmentitem_servicefaqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCaseBeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название кейса')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое описание')),
                ('before_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='services/cases/before/', verbose_name='Фото ДО')),
                ('after_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='services/cases/after/', verbose_name='Фото ПОСЛЕ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_before_after', to='cms.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Кейс До/После',
                'verbose_name_plural': 'Кейсы До/После',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('business_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип бизнеса (опционально)')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='services/clients/logos/', verbose_name='Логотип')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_companies', to='cms.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Компания-клиент',
                'verbose_name_plural': 'Кто уже заказывал',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('contract', 'Договор'), ('invoice', 'Счёт'), ('act', 'Акт'), ('other', 'Другое')], max_length=20, verbose_name='Тип документа')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (опционально)')),
                ('file', models.FileField(blank=True, null=True, upload_to='services/documents/', verbose_name='Файл')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка (если файл хранится где-то)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cms.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Документ услуги',
                'verbose_name_plural': 'Документы услуги',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceExcludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Не входит в услугу')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_items', to='cms.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Не входит (пункт)',
                'verbose_name_plural': 'Что НЕ входит',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequirementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Требование')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_items', to='cms.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Требование к объекту',
                'verbose_name_plural': 'Требования к объекту',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceWorkConditionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Условие')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_condition_items', to='cms.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Условие выполнения работ',
                'verbose_name_plural': 'Условия выполнения работ',
                'ordering': ['order', 'id'],
            },
        ),
    ]
