# Generated by Django 5.2 on 2026-01-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_servicecasebeforeafter_serviceclientcompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequirementitem',
            name='description',
            field=models.CharField(default=1, max_length=255, verbose_name='описание'),
            preserve_default=False,
        ),
    ]
